### ISSUE TITLE
Indexes for the same de Bruijn graph built from a different number of copies of the same FASTA file have different sizes

### ISSUE THREAD

**Issue by karel-brinda** [algbio/themisto#6]
When I wanted to evaluate how much space is occupied by the BOSS representation as implemented in Themisto, the following simple test failed: I build the index from a FASTA file and then from two copies of the same file. Clearly, both files contain the same k-mers. However, the obtained indexes are different:

```
cat ../pangenome-ngonorrhoeae.assembly18.fa > ngono.asm18_1cop.fa
(
        cat ../pangenome-ngonorrhoeae.assembly18.fa
        cat ../pangenome-ngonorrhoeae.assembly18.fa
) > ngono.asm18_2cop.fa

```

```
../../../themisto/bin/build_index --mem-megas 10000 --k 18 --input-file ngono.asm18_1cop.fa --n-threads 4 --index-dir index1cop --temp-dir tmp1cop

../../../themisto/bin/build_index --mem-megas 10000 --k 18 --input-file ngono.asm18_2cop.fa --n-threads 4 --index-dir index2cop --temp-dir tmp2cop
```

```
tar cvf - index1cop > index1cop.tar
tar cvf - index2cop > index2cop.tar
```

```
ls -alh index1cop.tar index2cop.tar 

-rw-rw-r-- 1 kb219 kb219 11M Nov  7 01:44 index1cop.tar
-rw-rw-r-- 1 kb219 kb219 13M Nov  7 01:44 index2cop.tar
```

```
(        echo index1cop
        ls -alh index1cop/*
        echo index2cop
        ls -alh index2cop/*
)

index1cop
-rw-rw-r-- 1 kb219 kb219    0 Nov  7 01:38 index1cop/boss-alphabet
-rw-rw-r-- 1 kb219 kb219 1.8K Nov  7 01:38 index1cop/boss-C
-rw-rw-r-- 1 kb219 kb219   11 Nov  7 01:38 index1cop/boss-constants
-rw-rw-r-- 1 kb219 kb219 2.2M Nov  7 01:38 index1cop/boss-indegs
-rw-rw-r-- 1 kb219 kb219 549K Nov  7 01:38 index1cop/boss-indegs_rs
-rw-rw-r-- 1 kb219 kb219 252K Nov  7 01:38 index1cop/boss-indegs_ss0
-rw-rw-r-- 1 kb219 kb219 264K Nov  7 01:38 index1cop/boss-indegs_ss1
-rw-rw-r-- 1 kb219 kb219 2.2M Nov  7 01:38 index1cop/boss-outdegs
-rw-rw-r-- 1 kb219 kb219 549K Nov  7 01:38 index1cop/boss-outdegs_rs
-rw-rw-r-- 1 kb219 kb219 252K Nov  7 01:38 index1cop/boss-outdegs_ss0
-rw-rw-r-- 1 kb219 kb219 264K Nov  7 01:38 index1cop/boss-outdegs_ss1
-rw-rw-r-- 1 kb219 kb219 3.7M Nov  7 01:38 index1cop/boss-outlabels-wt
index2cop
-rw-rw-r-- 1 kb219 kb219    0 Nov  7 01:44 index2cop/boss-alphabet
-rw-rw-r-- 1 kb219 kb219 1.9K Nov  7 01:44 index2cop/boss-C
-rw-rw-r-- 1 kb219 kb219   12 Nov  7 01:44 index2cop/boss-constants
-rw-rw-r-- 1 kb219 kb219 2.6M Nov  7 01:44 index2cop/boss-indegs
-rw-rw-r-- 1 kb219 kb219 661K Nov  7 01:44 index2cop/boss-indegs_rs
-rw-rw-r-- 1 kb219 kb219 303K Nov  7 01:44 index2cop/boss-indegs_ss0
-rw-rw-r-- 1 kb219 kb219 318K Nov  7 01:44 index2cop/boss-indegs_ss1
-rw-rw-r-- 1 kb219 kb219 2.6M Nov  7 01:44 index2cop/boss-outdegs
-rw-rw-r-- 1 kb219 kb219 661K Nov  7 01:44 index2cop/boss-outdegs_rs
-rw-rw-r-- 1 kb219 kb219 303K Nov  7 01:44 index2cop/boss-outdegs_ss0
-rw-rw-r-- 1 kb219 kb219 318K Nov  7 01:44 index2cop/boss-outdegs_ss1
-rw-rw-r-- 1 kb219 kb219 4.4M Nov  7 01:44 index2cop/boss-outlabels-wt

```

OS: OSX, Themisto version: 21a48ec8df30c27446016a2f0a193dac9b3aa7eb

**Comment by jnalanko** [comment]
Thank you for the good report. I think this could be due to how we handle letters outside of the alphabet A,C,G,T. If there is some other character, such as 'N', we replace it with a random character. This can generate different k-mers in the two copies. Does you input contain characters other than A,C,G,T?

**Comment by karel-brinda** [comment]
Thanks for the advice! This was indeed the reason. I fixed by running the following code for cleaning:
```
seqtk cutN -n1 "{input}" \\
                | seqtk seq -U -C -L18 \\
                | bioawk -c fastx '{{ print ">" ++i" \\n"$seq }}'
```

I think that replacing N by a random character can be a bit dangerous in the context of de Bruijn graph. It makes perfect sense for read mapping (e.g., BWA does that), but dBGs are a different story.  For instance, I often create the graphs by merging many sequence data files (e.g., several thousand assemblies, most of them very similar). Apparently, these randomly made-up k-mers can then become even more frequent than the true ones. Have you considered just skipping those k-mers that contain non-ACGT?

**Comment by karel-brinda** [comment]
I thought a lot about the possible use cases and I know can imagine situations when replacing N by a random nucleotide can be useful. So maybe adding a command-line option could be a solution?

**Comment by jnalanko** [comment]
Hi Karel. Ignoring k-mers with character N is not a quick change in the code, because the code assumes that every k-mer has both an in-neighbor and an out-neighbor. To make this hold, currently we concatenate every input sequence, separating them with dollar signs, and index all cyclic k-mers of the concatenation.

Otherwise, to maintain the underlying Wheeler graph data structure, we would need to add every prefix s-mer of length s=0,...,k-1 of every k-mer that has in-degree 0 to make the query data structure work correctly. It's possible, but not a quick change. This would also remove the need for the dollar concatenation trick, which could improve the space usage. In the case when we index long sequences like genomes, the overhead of the dollars is negligible, but if we would index, say, short reads, the situation might be different.

This improvement could come in the next release of the software. Currently I am quite busy with other things, so it wont happen very soon. Thank you for the suggestion anyway. Appreciated!

**Comment by jnalanko** [comment]
The index structure has now been improved significantly, which made it possible to add a flag `--delete-non-ACGT`that deletes all k-mers that contain a non-ACGT-characters. Issue closed!
